# Generated by Django 5.1.3 on 2025-01-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
