# Generated by Django 5.1.3 on 2025-01-02 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_remove_booking_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='utility',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='isworkroom',
            field=models.BooleanField(default=False),
        ),
    ]
