# Generated by Django 5.1.3 on 2025-01-03 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0005_rename_capacity_room_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
