# Generated by Django 5.1.4 on 2025-01-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_remove_booking_time_slot_booking_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.IntegerField(default=1),
        ),
    ]
