# Generated by Django 5.1.3 on 2025-01-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0007_rename_room_booking_room_id_room_building_and_more'),
        ('bookingsystem', '0008_booking_course'),
    ]

    operations = [
    ]
